### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by MAdil45** [Guepardow/Visual-features#1]
Hi. Awesome work.  I am trying to run the network. However, I am getting this error which i couldn't figure out. Could you please look into it or guide me into the right direction. 
P.S. I am a very new to this. Thanks in advance. 
![Screenshot from 2020-11-17 15-41-57](https://user-images.githubusercontent.com/36837450/99360445-8d6ba600-28eb-11eb-8403-cac9647fcf6b.png)

**Comment by Guepardow** [comment]
Hi @MAdil45. I am glad you find this work awesome ! 
Have you checked the path to the images ? Normally, it should be something like this : `<PATH_DATA>/DETRAC/Insight-MVT_Annotation_Train/MVI_20011/img00001.jpg`, where `<PATH_DATA>` is the path specified in the `dataset.py` file.

I have just added an assert statement in the code to verify that the image is properly opened.

**Comment by MAdil45** [comment]
@Guepardow Thank you so much for the response. It is solved and working now. However, I am getting another error, Could you please look into it or you can guide me in the right direction. Thanks. Following are the details. 

raise ValueError("Invalid color argument: ''")
ValueError: Invalid color argument: ''

![Screenshot from 2020-11-20 11-38-43](https://user-images.githubusercontent.com/36837450/99755187-16b9ed00-2b25-11eb-99b9-f4233d7670b6.png)

**Comment by MAdil45** [comment]
@Guepardow Could you please look into it. I am waiting for your response. I have tried but I couldn't find satisfied solution. 
Thanks. Looking forward to hear from you.
