### ISSUE TITLE
Invalid color argument

### ISSUE THREAD

**Issue by Guepardow** [Guepardow/Visual-features#2]
@Guepardow Thank you so much for the response. It is solved and working now. However, I am getting another error, Could you please look into it or you can guide me in the right direction. Thanks. Following are the details. 

raise ValueError("Invalid color argument: ''")
ValueError: Invalid color argument: ''

![Screenshot from 2020-11-20 11-38-43](https://user-images.githubusercontent.com/36837450/99755187-16b9ed00-2b25-11eb-99b9-f4233d7670b6.png)

_Originally posted by @MAdil45 in https://github.com/Guepardow/Visual-features/issues/1#issuecomment-730824841_

**Comment by Guepardow** [comment]
Hi, do you have any data in the file `df_logs` ? Otherwise, you need to run the `main.py` on the whole dataset.

For your convenience, I have just added the folder `script` which contains some bash scripts to automaticallly run `main.py` on a whole dataset.
I also noticed that I missed the appearance vehReid so please git pull the code.

**Comment by MAdil45** [comment]
@Guepardow Hi. Yes, exactly. I only had data from one specific scene and with only one feature of resnet18, that is why I was getting that error. Now, thanks to you for uploading the script, I am training it for the whole dataset. I am sure this time i won't face that error. You can close this issue now.
